from colossalai.amp import AMP_TYPE
import os

DATA_DIR = "/scratch/prj/bayunet/dhcp_lores"
OUTPUT_DIR = "/scratch/prj/bayunet/experiments/output_gan"
AUGMENTATION=False
INPUT_MODALITIES=["t2"]
OUTPUT_MODALITIES=["t2"]
BATCH_SIZE=32
IN_CHANNELS=1
OUT_CHANNELS=1
NUM_EPOCHS=1000
N_SPLITS=5
F_MAPS=[16, 32, 64, 128, 256]

WARMUP_EPOCHS=None
LR=0.001
NUM_SAMPLES=None
LATENT_SIZE = 8
ALPHA = 0.00025
DOWN_FACTOR = 5
DATASET='dHCP'