from .synth_dhcp_dataloader import get_dataloader as get_synth_dhcp_dataloader
from .synth_hcp_dataloader import get_dataloader as get_synth_hcp_dataloader
from .synth_brats_dataloader import get_dataloader as get_synth_brats_dataloader
from .synth_dolphin_dataloader import get_dataloader as get_synth_dolphin_dataloader