from colossalai.amp import AMP_TYPE
import os

DATA_DIR = '/home/levibaljer/FLYWHEEL_DOLPHIN/T2_Inputs_and_Targets/'
OUTPUT_DIR = '/home/levibaljer/FLYWHEEL_DOLPHIN/Outputs/'
AUGMENTATION=False
INPUT_MODALITIES=["t2"]
OUTPUT_MODALITIES=["t2"]
BATCH_SIZE=2
IN_CHANNELS=3
OUT_CHANNELS=1
NUM_EPOCHS=1000
N_SPLITS=5
F_MAPS=[16, 32, 64, 128, 256]

VAE=False

WARMUP_EPOCHS=None
LR=0.001
NUM_SAMPLES=None
LATENT_SIZE = 8
ALPHA = 0.00025
DOWN_FACTOR = 5
DATASET='Dolphin'